name = "ParallelGraphs"
uuid = "4cdd4def-cb7e-45de-811d-e1afe4aa22cb"
authors = ["KassFlute <cassien.roth@epfl.ch> and contributors"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Graphs = "1.9"
julia = "1.10"
DataStructures = "0.18"
