name = "ParallelGraphs"
uuid = "4cdd4def-cb7e-45de-811d-e1afe4aa22cb"
authors = ["KassFlute <cassien.roth@epfl.ch> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
